### ISSUE TITLE
Unable to start the program

### ISSUE THREAD

**Issue by native-api** [mbr/pypi-classifiers#1]
The only source file in the package, `pypiclassifiers\__init__.py`, is empty. So I've no idea how to start the darn thing (c) (and if it's supposed to work at all).

Could you reflect this in README.md or something, or, at least, tell me here?

**Comment by mbr** [comment]
The tool is 4 years old and during that time, Gtk2+Python has been somewhat deprecated. I've updated the source, made it self-contained and updated to the `gi.repository`-style imports of Gtk3.

It should work out of the box now. Check the new `README.rst` and let me know if you still have issues.
